{{- if and .Values.secret .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
