{{- if and .Values.slackSecret .Values.slackSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slackSecret.name | quote }}
type: Opaque
stringData:
  SLACK_BOT_TOKEN: {{ index .Values.slackSecret.stringData "SLACK_BOT_TOKEN" | quote }}
  SLACK_CHANNEL_ID: {{ index .Values.slackSecret.stringData "SLACK_CHANNEL_ID" | quote }}
{{- end }}
