{{- if .Values.marketfeeder.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botsquadron.fullname" . }}-marketfeeder
  namespace: {{ .Release.Namespace }}
  labels:
    app: marketfeeder
    app.kubernetes.io/name: marketfeeder
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: botsquadron
spec:
  replicas: {{ .Values.marketfeeder.replicas }}
  selector:
    matchLabels:
      app: marketfeeder
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: marketfeeder
        app.kubernetes.io/name: marketfeeder
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: botsquadron
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: marketfeeder
          image: "{{ include "botsquadron.image" (dict "root" . "service" "marketfeeder" "image" .Values.marketfeeder.image) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "botsquadron.configMapName" . }}
            {{- if and .Values.secret .Values.secret.enabled }}
            - secretRef:
                name: {{ include "botsquadron.secretName" . }}
            {{- end }}
          resources:
{{ toYaml .Values.marketfeeder.resources | indent 12 }}
{{- end }}