{{- if .Values.ordersystem.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "botsquadron.ordersystemName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ordersystem
    app.kubernetes.io/name: ordersystem
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: botsquadron
spec:
  type: {{ .Values.ordersystem.service.type }}
  selector:
    app: ordersystem
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.ordersystem.service.port }}
      targetPort: http
{{- end }}
