{{- if .Values.solobot.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "botsquadron.fullname" . }}-solobot
  namespace: {{ .Release.Namespace }}
  labels:
    app: solobot
    app.kubernetes.io/name: solobot
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: botsquadron
  {{- with .Values.solobot.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.solobot.backoffLimit }}
  {{- with .Values.solobot.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        app: solobot
        app.kubernetes.io/name: solobot
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: botsquadron
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
      restartPolicy: {{ .Values.solobot.restartPolicy }}
      containers:
        - name: solobot
          image: "{{ include "botsquadron.image" (dict "root" . "service" "solobot" "image" .Values.solobot.image) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{ toYaml .Values.solobot.args | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "botsquadron.configMapName" . }}
            {{- if and .Values.secret .Values.secret.enabled }}
            - secretRef:
                name: {{ include "botsquadron.secretName" . }}
            {{- end }}
          resources:
{{ toYaml .Values.solobot.resources | indent 12 }}
{{- end }}