{{- if and .Values.secret .Values.secret.enabled .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "taperecorder-secrets" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
