image:
  repository: docker.io/bizzkpm/taperecorder
  tag: "sha-5c677a5"
  pullPolicy: IfNotPresent

env:
  PROJECT_ROOT: /app
  DATA_ROOT: /app/data
  TZ: Asia/Kolkata
  DUCKDB_MEMORY_LIMIT: "2GB"
  DUCKDB_THREADS: "2"
  UPSTOX_API_ACCESS_TOKEN: "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI3QkFYVDYiLCJqdGkiOiI2YTZmZjViMDM4OGM5MDUyYjBhZTg5ZjYiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzg1NzIyMjg4LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3ODU3OTQ0MDB9.mOU3pJvU6OxH5Sic25rVYe2wkaGnTkYHTT7-kfU1YGY"
  EXECUTION_MODE: "production"
  NIFTY50_FUTURE: "NSE_FO|58072"
  STOCK_MONTHLY_EXPIRY: "2026-08-25"
  DO_S3_ENDPOINT_URL: "https://sgp1.digitaloceanspaces.com"
  DO_S3_REGION: "sgp1"
  DO_S3_BUCKET_NAME: "index-bucket"
  DO_S3_SPACES_PREFIX: "index-bucket-holder/contracts"
  DO_S3_ACCESS_KEY_ID: "DO00HTRKUMPEG449UQQF"
  DO_S3_SECRET_ACCESS_KEY: "ylqc648Tf6pIyx+VAGQYYqfLJk6ck7sD8Z4tdZPjRk0"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"

  limits:
    cpu: "2"
    memory: "3Gi"

pvc:
  enabled: true
  size: 3Gi
