image:
  repository: docker.io/bizzkpm/taperecorder
  tag: "sha-f495cdc"
  pullPolicy: IfNotPresent

env:
  PROJECT_ROOT: /app
  DATA_ROOT: /app/data
  TZ: Asia/Kolkata
  DUCKDB_MEMORY_LIMIT: "2GB"
  DUCKDB_THREADS: "2"
  UPSTOX_API_ACCESS_TOKEN: "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI3QkFYVDYiLCJqdGkiOiI2YWI5ZGRhYTJjNjdlYjczYzE1NjhkMDYiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzkwNTY1ODAyLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3OTA2MzI4MDB9.0MYwZYJsyz2u0Z6c5Zcnb0gvstGXBeePblzDgXZuTlY"
  NIFTY50_FUTURE: "NSE_FO|48704"
  STOCK_MONTHLY_EXPIRY: "2026-10-27"
  STOCK_MONTHLY_EXPIRY: "2026-09-29"
  DO_S3_ENDPOINT_URL: "https://sgp1.digitaloceanspaces.com"
  DO_S3_REGION: "sgp1"
  DO_S3_BUCKET_NAME: "index-bucket"
  DO_S3_SPACES_PREFIX: "index-bucket-holder/contracts"
  DO_S3_ACCESS_KEY_ID: "DO00HTRKUMPEG449UQQF"
  DO_S3_SECRET_ACCESS_KEY: "ylqc648Tf6pIyx+VAGQYYqfLJk6ck7sD8Z4tdZPjRk0"

  CLOUDPE_S3_ENDPOINT_URL: https://s3.in-west2.purestore.io
  CLOUDPE_S3_REGION: in-west2
  CLOUDPE_S3_BUCKET_NAME: index-bucket
  CLOUDPE_S3_PREFIX: index-bucket-holder/contracts
  CLOUDPE_S3_SECRET_ACCESS_KEY: R8VUoxQ0FTrfDPETEG2SXT06zGL7Jzew4RsG5KkA
  CLOUDPE_S3_ACCESS_KEY_ID: f5c29933a66353f4CT6L

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"

  limits:
    cpu: "2"
    memory: "3Gi"

pvc:
  enabled: true
  size: 3Gi
